export const COUNTRY_NAMES = {
  AF: "Afghanistan", AL: "Albanie", DZ: "Algerie", AD: "Andorre", AO: "Angola",
  AR: "Argentine", AM: "Armenie", AU: "Australie", AT: "Autriche", AZ: "Azerbaidjan",
  BH: "Bahrein", BD: "Bangladesh", BE: "Belgique", BJ: "Benin", BT: "Bhoutan",
  BO: "Bolivie", BA: "Bosnie", BR: "Bresil", BN: "Brunei", BG: "Bulgarie",
  BF: "Burkina Faso", BI: "Burundi", KH: "Cambodge", CM: "Cameroun", CA: "Canada",
  CL: "Chili", CN: "Chine", CO: "Colombie", KM: "Comores", CG: "Congo",
  CR: "Costa Rica", CI: "Cote d'Ivoire", HR: "Croatie", CU: "Cuba", CY: "Chypre",
  CZ: "Tchequie", DK: "Danemark", DJ: "Djibouti", DO: "Rep. Dominicaine",
  EC: "Equateur", EG: "Egypte", SV: "Salvador", GQ: "Guinee equatoriale",
  EE: "Estonie", ET: "Ethiopie", FI: "Finlande", FR: "France", GA: "Gabon",
  GE: "Georgie", DE: "Allemagne", GH: "Ghana", GR: "Grece", GT: "Guatemala",
  GN: "Guinee", HT: "Haiti", HN: "Honduras", HK: "Hong Kong", HU: "Hongrie",
  IS: "Islande", IN: "Inde", ID: "Indonesie", IR: "Iran", IQ: "Irak",
  IE: "Irlande", IL: "Israel", IT: "Italie", JM: "Jamaique", JP: "Japon",
  JO: "Jordanie", KZ: "Kazakhstan", KE: "Kenya", KW: "Koweit", KG: "Kirghizistan",
  LA: "Laos", LV: "Lettonie", LB: "Liban", LY: "Libye", LI: "Liechtenstein",
  LT: "Lituanie", LU: "Luxembourg", MG: "Madagascar", MY: "Malaisie", ML: "Mali",
  MT: "Malte", MR: "Mauritanie", MU: "Maurice", MX: "Mexique", MD: "Moldavie",
  MC: "Monaco", MN: "Mongolie", ME: "Montenegro", MA: "Maroc", MZ: "Mozambique",
  MM: "Myanmar", NA: "Namibie", NP: "Nepal", NL: "Pays-Bas", NZ: "Nouvelle-Zelande",
  NI: "Nicaragua", NE: "Niger", NG: "Nigeria", NO: "Norvege", OM: "Oman",
  PK: "Pakistan", PA: "Panama", PY: "Paraguay", PE: "Perou", PH: "Philippines",
  PL: "Pologne", PT: "Portugal", QA: "Qatar", RO: "Roumanie", RU: "Russie",
  RW: "Rwanda", SA: "Arabie Saoudite", SN: "Senegal", RS: "Serbie",
  SG: "Singapour", SK: "Slovaquie", SI: "Slovenie", ZA: "Afrique du Sud",
  KR: "Coree du Sud", ES: "Espagne", LK: "Sri Lanka", SD: "Soudan",
  SE: "Suede", CH: "Suisse", SY: "Syrie", TW: "Taiwan", TZ: "Tanzanie",
  TH: "Thailande", TG: "Togo", TN: "Tunisie", TR: "Turquie", UA: "Ukraine",
  AE: "Emirats arabes unis", GB: "Royaume-Uni", US: "Etats-Unis", UY: "Uruguay",
  UZ: "Ouzbekistan", VE: "Venezuela", VN: "Vietnam", YE: "Yemen", ZM: "Zambie",
  ZW: "Zimbabwe", CD: "RD Congo", TL: "Timor oriental", SS: "Soudan du Sud",
  XK: "Kosovo", PS: "Palestine",
};

export const COUNTRY_CONTINENTS = {
  AF: "Asie", AL: "Europe", DZ: "Afrique", AD: "Europe", AO: "Afrique",
  AR: "Amerique", AM: "Asie", AU: "Oceanie", AT: "Europe", AZ: "Asie",
  BH: "Asie", BD: "Asie", BE: "Europe", BJ: "Afrique", BT: "Asie",
  BO: "Amerique", BA: "Europe", BR: "Amerique", BN: "Asie", BG: "Europe",
  BF: "Afrique", BI: "Afrique", KH: "Asie", CM: "Afrique", CA: "Amerique",
  CL: "Amerique", CN: "Asie", CO: "Amerique", KM: "Afrique", CG: "Afrique",
  CR: "Amerique", CI: "Afrique", HR: "Europe", CU: "Amerique", CY: "Europe",
  CZ: "Europe", DK: "Europe", DJ: "Afrique", DO: "Amerique",
  EC: "Amerique", EG: "Afrique", SV: "Amerique", GQ: "Afrique",
  EE: "Europe", ET: "Afrique", FI: "Europe", FR: "Europe", GA: "Afrique",
  GE: "Asie", DE: "Europe", GH: "Afrique", GR: "Europe", GT: "Amerique",
  GN: "Afrique", HT: "Amerique", HN: "Amerique", HK: "Asie", HU: "Europe",
  IS: "Europe", IN: "Asie", ID: "Asie", IR: "Asie", IQ: "Asie",
  IE: "Europe", IL: "Asie", IT: "Europe", JM: "Amerique", JP: "Asie",
  JO: "Asie", KZ: "Asie", KE: "Afrique", KW: "Asie", KG: "Asie",
  LA: "Asie", LV: "Europe", LB: "Asie", LY: "Afrique", LI: "Europe",
  LT: "Europe", LU: "Europe", MG: "Afrique", MY: "Asie", ML: "Afrique",
  MT: "Europe", MR: "Afrique", MU: "Afrique", MX: "Amerique", MD: "Europe",
  MC: "Europe", MN: "Asie", ME: "Europe", MA: "Afrique", MZ: "Afrique",
  MM: "Asie", NA: "Afrique", NP: "Asie", NL: "Europe", NZ: "Oceanie",
  NI: "Amerique", NE: "Afrique", NG: "Afrique", NO: "Europe", OM: "Asie",
  PK: "Asie", PA: "Amerique", PY: "Amerique", PE: "Amerique", PH: "Asie",
  PL: "Europe", PT: "Europe", QA: "Asie", RO: "Europe", RU: "Europe",
  RW: "Afrique", SA: "Asie", SN: "Afrique", RS: "Europe",
  SG: "Asie", SK: "Europe", SI: "Europe", ZA: "Afrique",
  KR: "Asie", ES: "Europe", LK: "Asie", SD: "Afrique",
  SE: "Europe", CH: "Europe", SY: "Asie", TW: "Asie", TZ: "Afrique",
  TH: "Asie", TG: "Afrique", TN: "Afrique", TR: "Europe", UA: "Europe",
  AE: "Asie", GB: "Europe", US: "Amerique", UY: "Amerique",
  UZ: "Asie", VE: "Amerique", VN: "Asie", YE: "Asie", ZM: "Afrique",
  ZW: "Afrique", CD: "Afrique",
};

// ISO 3166-1 numeric to alpha-2 mapping for topojson
export const NUMERIC_TO_ALPHA2 = {
  4: "AF", 8: "AL", 12: "DZ", 20: "AD", 24: "AO", 32: "AR", 51: "AM",
  36: "AU", 40: "AT", 31: "AZ", 48: "BH", 50: "BD", 56: "BE", 204: "BJ",
  64: "BT", 68: "BO", 70: "BA", 76: "BR", 96: "BN", 100: "BG", 854: "BF",
  108: "BI", 116: "KH", 120: "CM", 124: "CA", 152: "CL", 156: "CN",
  170: "CO", 174: "KM", 178: "CG", 188: "CR", 384: "CI", 191: "HR",
  192: "CU", 196: "CY", 203: "CZ", 208: "DK", 262: "DJ", 214: "DO",
  218: "EC", 818: "EG", 222: "SV", 226: "GQ", 233: "EE", 231: "ET",
  246: "FI", 250: "FR", 266: "GA", 268: "GE", 276: "DE", 288: "GH",
  300: "GR", 320: "GT", 324: "GN", 332: "HT", 340: "HN", 344: "HK",
  348: "HU", 352: "IS", 356: "IN", 360: "ID", 364: "IR", 368: "IQ",
  372: "IE", 376: "IL", 380: "IT", 388: "JM", 392: "JP", 400: "JO",
  398: "KZ", 404: "KE", 414: "KW", 417: "KG", 418: "LA", 428: "LV",
  422: "LB", 434: "LY", 438: "LI", 440: "LT", 442: "LU", 450: "MG",
  458: "MY", 466: "ML", 470: "MT", 478: "MR", 480: "MU", 484: "MX",
  498: "MD", 492: "MC", 496: "MN", 499: "ME", 504: "MA", 508: "MZ",
  104: "MM", 516: "NA", 524: "NP", 528: "NL", 554: "NZ", 558: "NI",
  562: "NE", 566: "NG", 578: "NO", 512: "OM", 586: "PK", 591: "PA",
  600: "PY", 604: "PE", 608: "PH", 616: "PL", 620: "PT", 634: "QA",
  642: "RO", 643: "RU", 646: "RW", 682: "SA", 686: "SN", 688: "RS",
  702: "SG", 703: "SK", 705: "SI", 710: "ZA", 410: "KR", 724: "ES",
  144: "LK", 736: "SD", 752: "SE", 756: "CH", 760: "SY", 158: "TW",
  834: "TZ", 764: "TH", 768: "TG", 788: "TN", 792: "TR", 804: "UA",
  784: "AE", 826: "GB", 840: "US", 858: "UY", 860: "UZ", 862: "VE",
  704: "VN", 887: "YE", 894: "ZM", 716: "ZW", 180: "CD",
};

export function countryCodeToFlag(code) {
  if (!code || code.length !== 2) return "";
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}
